KDAcalculator/Controllers/StatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PresentationLayer.Models;
using DataAccessLayer;
using LogicLayer;

namespace PresentationLayer.Controllers
{
    public class StatsController : Controller
    {        
            //Mappers
            static PLMapper _mapper = new PLMapper();
            static DataAccess _StatDataAccess = new DataAccess();
            static StatsLogic _StatLogic = new StatsLogic();


            // GET: Stats
            public ActionResult Index()
            {
                return View();
            }
        //Adding Stats
        [HttpPost]
        public ActionResult StatsAdd(StatsModel _AddStats)
        {
            if (ModelState.IsValid)
            {
                _StatLogic.AddStats(_mapper.Map(_AddStats));
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpGet]
        public ActionResult StatsAdd()
        {
            StatsModel _Stats = new StatsModel();
            return View(_Stats);

        }
        //Update Team Information
        [HttpPost]
        public ActionResult StatsUpdate(StatsModel _UpdateStats)
        {
            if (ModelState.IsValid)
            {     
                //send the input information to the Logic Layer for the calculation to happen
                _StatLogic.AddStats(_mapper.Map(_UpdateStats));
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpGet]
        public ActionResult StatsUpdate()
        {
            StatsModel _UpdateStats = new StatsModel();
            return View(_UpdateStats);

        }
        [HttpGet]
        public ActionResult StatsView()
        {

            if (ModelState.IsValid)
            {
                StatsList _ListStats = new StatsList();
                _ListStats._StatsList = _mapper.Map(_StatDataAccess.GetAllStats());
                return View(_ListStats);
            }
            return View();
        }
    }
}

KDAcalculator/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PresentationLayer.Models;
using DataAccessLayer;



namespace PresentationLayer.Controllers
{
    public class TeamsController : Controller
    {
        //Mapper
        static PLMapper _mapper = new PLMapper();
        static DataAccess _TeamDataAccess = new DataAccess();

        // GET: Teams
        public ActionResult Index()
        {
            return View();
        }        
        //Register Team
        [HttpPost]
        public ActionResult TeamRegister(TeamsModel _RegTeam)
        {
            if (ModelState.IsValid)
            {
                _TeamDataAccess.AddTeams(_mapper.Map(_RegTeam));
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpGet]
        public ActionResult TeamRegister()
        {
            TeamsModel _Teams = new TeamsModel();
            return View(_Teams);

        }
        //Update Team Information
        [HttpPost]
        public ActionResult TeamUpdate(TeamsModel _UpdateTeams)
        {
            if (ModelState.IsValid)
            {
                _UpdateTeams.TeamName = (string)Session["TeamName"];
                _TeamDataAccess.UpdateTeams(_mapper.Map(_UpdateTeams));
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpGet]
        public ActionResult TeamUpdate()
        {
            TeamsModel _UpdateTeam = new TeamsModel();
            return View(_UpdateTeam);

        }
        //TeamList view
        [HttpGet]
        public ActionResult TeamView()
        {

            if (ModelState.IsValid)
            {
                TeamList _ListTeams = new TeamList();
                _ListTeams._TeamsList = _mapper.Map(_TeamDataAccess.GetAllTeams());
                return View(_ListTeams);
            }
            return View();
        }
    }
}

KDAcalculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Halo Stat Calculator</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Halo Stat Calculator", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Session["PlayerName"] == null)
                    {
                        <li>@Html.ActionLink("Login", "Login", "Player")</li>
                        <li>@Html.ActionLink("Register", "PlayerRegister", "Player")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Update Profile", "PlayerUpdate", "Player")</li>
                        <li>@Html.ActionLink("LogOut", "LogOut", "Player")</li>
                    }
                    @if (Session["PlayerName"] != null && (int)Session["FKRoleID"] >= 2)
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown">
                                More Options
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Team Registration", "TeamRegister", "Teams")</li>
                                <li>@Html.ActionLink("Team Update", "TeamUpdate", "Teams")</li>
                                <li>@Html.ActionLink("Add/Updating Stats", "StatsUpdate", "Stats")</li>


                                @if ((int)Session["FKRoleID"] == 3)
                                {
                                    <li>@Html.ActionLink("Admin Update", "AdminUpdate", "Player")</li>
                                }
                            </ul>
                        </li>                       
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Halo Stat App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>