KDAcalculator/Controllers/ComingSoonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    public class ComingSoonController : Controller
    {           
        public ActionResult ComingSoon()
        {           
            return View();
        }
    }
}

KDAcalculator/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

KDAcalculator/Controllers/StatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PresentationLayer.Models;
using DataAccessLayer;
using LogicLayer;

namespace PresentationLayer.Controllers
{
    public class StatsController : Controller
    {        
            //Mappers
            static PLMapper _mapper = new PLMapper();
            static DataAccess _StatDataAccess = new DataAccess();
            static StatsLogic _StatLogic = new StatsLogic();


            // GET: Stats
            public ActionResult Index()
            {
                return View();
            }
        //Adding Stats
        [HttpPost]
        public ActionResult StatsAdd(StatsModel _AddStats)
        {
            if (ModelState.IsValid)
            {
                _StatLogic.AddStats(_mapper.Map(_AddStats));
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpGet]
        public ActionResult StatsAdd()
        {
            StatsModel _Stats = new StatsModel();
            return View(_Stats);

        }
        //Update Team Information
        [HttpPost]
        public ActionResult StatsUpdate(StatsModel _UpdateStats)
        {
            if (ModelState.IsValid)
            {     
                //send the input information to the Logic Layer for the calculation to happen
                _StatLogic.AddStats(_mapper.Map(_UpdateStats));
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpGet]
        public ActionResult StatsUpdate()
        {
            StatsModel _UpdateStats = new StatsModel();
            return View(_UpdateStats);

        }
        [HttpGet]
        public ActionResult StatsView()
        {

            if (ModelState.IsValid)
            {
                StatsList _ListStats = new StatsList();
                _ListStats._StatsList = _mapper.Map(_StatDataAccess.GetAllStats());
                return View(_ListStats);
            }
            return View();
        }
    }
}

KDAcalculator/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

KDAcalculator/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

KDAcalculator/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>WELCOME</h1>
    <p class="lead">Thanks for coming. This App is designed to generate updated Personal and Team KDA's after each game. We Hope You enjoy.</p>    
</div>

<div class="row">
    @if (Session["PlayerName"] == null)
    {
        <div class="col-md-4">
            <h2>Things are hidden!</h2>
            <p>
                You Currently Are Not Logged In. Please Log In To Have Access To The Hidden Aspects.
            </p>
            <p>@Html.ActionLink("Please Log In", "Login", "Player", null, new { @class = "btn btn-default" })</p>
        </div>
    }
    else
    {
    <div class="col-md-4">
        <h2>View Players</h2>
        <p>
            Here you can see a list of all Players.
        </p>
        <p>@Html.ActionLink("Players", "PlayerView", "Player", null, new { @class = "btn btn-default" })</p>
    </div>

    <div class="col-md-4">
        <h2>View Teams</h2>
        <p>Here you will be able to view the List of Teams.</p>
        <p>@Html.ActionLink("Teams", "TeamView", "Teams", null, new { @class = "btn btn-default" })</p>
    </div>

    <div class="col-md-4">
        <h2>Player LeaderBoard</h2>
        <p>Here is the Player Leaderboard based on higest KDAs.</p>
        <p>@Html.ActionLink("Player Stats", "StatsView", "Stats", null, new { @class = "btn btn-default" })</p>
    </div>

    <div class="col-md-4">
        <h2>Team LeaderBoard</h2>
        <p>Here can view the Team Leaderboard based on the Highest Team KDAs.</p>
        <p>@Html.ActionLink("TeamsLeaderBoard", "ComingSoon", "ComingSoon", null, new { @class = "btn btn-default" })</p>
    </div>
    }
</div>